logging:
  level:
    org.springframework: WARN

server:
  server-header:

security:
  api_users_config_path: classpath:/accounts-api-users.yml

spring:
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/accounts?autoReconnect=true&useSSL=false
    username: root
    password:
  main:
    banner-mode: "off"

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
